version: '3.7'

services:

  # |---------------|
  # |   Portainer   |
  # |---------------|

  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - LETSENCRYPT_HOST={{portainer_domain}}
      - VIRTUAL_HOST={{portainer_domain}}
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: